version: "2"
services:
  elk:
    container_name: elk_logs
    image: sebp/elk
    restart: always
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    environment:
     - ELASTICSEARCH_START=1
     - LOGSTASH_START=0
     - KIBANA_START=1
    volumes:
     - D:\data\elk\elasticsearchDB:/var/lib/elasticsearch
     - D:\data\elk\elasticLog:/var/log/elasticsearch
     - D:\data\elk\kibanaLog:/var/log/kibana
